[Raspberry]
# Extra variable, it is used to identify the Raspberry
# Here, for a ZMQ link, we use an IPv4 address to connect to the Raspberry via Ethernet
address_Rasp = '192.158.235.2'
port = '5555'
#

[Raspberry.ACTUATOR.COMPONENT1]
# Basic variables, you need them for the plugin to work correctly !
title = "MyActuator" # IT HAVE TO BE UNIQUE AMONG THE OTHER COMPONENT'S NAME
name = "nameActuator" # IT HAVE TO BE UNIQUE AMONG THE OTHER COMPONENT'S NAME
units = ""
min = "0"
max = "100"
#
# Extra variables, they are used to identify the component
# Here, for a I2C network, we use an address and a pin variable to identify and use the component "MyActuator"
address = "None"
pin = "00"
#

#[Raspberry.ACTUATOR.COMPONENT2]
#title = ""
#name = ""
#units = ""
#min = ""
#max = ""

[Raspberry.DETECTOR.COMPONENT1]
# Basic variables, you need them for the plugin to work correctly !
title = "MyDetector" # IT HAVE TO BE UNIQUE AMONG THE OTHER COMPONENT'S NAME
name = "nameDetector" # IT HAVE TO BE UNIQUE AMONG THE OTHER COMPONENT'S NAME
units = "V"
#
# Extra variables, they are used to identify the component
# Here, for a I2C network, we use an address and a pin variable to identify and use the component "MyActuator"
address = "0x00"
pin = "None"
#

#[Raspberry.DETECTOR.COMPONENT2]
#title = ""
#name = ""
#units = ""
